'use strict';
const width = 55;
const height = 23;
const area = width * height;
console.log('value of area: ' + area);
console.log('typeof area: ' + typeof area);
const bill = 11;
const payment = 21;
const change = bill - payment;
console.log('value of change: ' + change);
console.log('typeof change: ' + typeof change);
const quizzes = 2;
const midterm = 5;
const final = 7;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade: ' + grade);
console.log('typeof grade: ' + typeof grade);
const firstName = 'Adam ';
const lastName = 'Zdravkovic';
const fullName = firstName + lastName;
console.log('value of fullName: ' + fullName);
console.log('typeof fullName: ' + typeof fullName);
const pH = 8;
const isAcidic = pH < 7;
console.log('value of isAcidic: ' + isAcidic);
console.log('typeof isAcidic: ' + typeof isAcidic);
const headCount = 15;
const isSparta = headCount === 300;
console.log('value of isSparta: ' + isSparta);
console.log('typeof isSparta: ' + typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('value of motto: ' + motto);
console.log('typeof motto: ' + typeof motto);
